### ISSUE TITLE
Violentmonkey @match incompatibilty

### ISSUE THREAD

**Issue by abcxff** [supahero1/diep_api#1]
I tried running the example scripts, but they didn't match to diep.io correctly.
```js
// @match https://diep.io
```
should be switched to
```js
// @match https://diep.io/
```

**Comment by supahero1** [comment]
countless scripts match to diep.io without the last dash and they work. additionally, the examples work for me and 2 other people that i tested them with. it must be a mistake on your side.

**Comment by supahero1** [comment]
these countless scripts include for instance unlag, eval packet overrider, advanced multibox.

**Comment by abcxff** [comment]
I see, it is violentmonkey. The example scripts and all the ones you listed do not have violentmonkey compatibility. Its up to you if you want to fix that or not, but atleast now you know.
